spring.application.name=parking-management-system

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/parking_management_system?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always

app.jwt.secret=change-this-secret-key-change-this-secret-key-123456
app.jwt.expiration-millis=86400000
app.bootstrap.admin-email=admin@pms.com
app.bootstrap.admin-password=Admin@123
app.bootstrap.admin-name=System Admin
app.file.upload-dir=uploads

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

razorpay.key.id=rzp_test_SlxlzJRDcLnEdl
razorpay.key.secret=68jset4bTXe39Q5S4o2PrqoT
